"""Vocabulaire ACP restreint : corrections phonetiques + context bias Voxtral.

Version reduite pour la v4 (1067 -> ~150 LOC). Toute la logique
d'acronymes, wordboost, expansions IHC et negations a ete retiree :
elle n'etait plus utilisee par le pipeline et Claude gere ces
transformations nativement via le prompt structure.

Seules deux fonctions sont exportees :
- ``corriger_phonetique(texte)`` : applique les corrections STT recurrentes
- ``get_context_bias()`` : retourne les termes biases pour Voxtral
"""

import re


CORRECTIONS_PHONETIQUES: dict[str, str] = {
    # ── Erreurs existantes du système ─────────────────────────────────────
    "branchique": "bronchique",
    "branchiques": "bronchiques",
    "en plan chic": "bronchique",
    "mucose": "muqueuse",
    "équeuse": "muqueuse",
    "équeuse branchique": "muqueuse bronchique",
    "fibro-yalin": "fibro-hyalin",
    # "trauma" volontairement retire : mot medical legitime (trauma, traumatisme)
    "racineuse": "acineuse",
    "dtf1": "TTF1",
    "yaline": "hyaline",
    "cananal": "canal anal",
    "ulière": "hilaire",
    "parenchymate": "parenchymateuse",
    # ── Corrections critiques découvertes sur audio réel ────────────────
    "tu meurs": "tumeur",
    "tu meurs sous la plèvre": "tumeur sous-pleurale",
    "mycosécrétion": "mucosécrétion",
    "pépillaire": "papillaire",
    "métaganglionnaire": "métastase ganglionnaire",
    "pas de métaganglionnaire": "absence de métastase ganglionnaire",
    "entraparenchymateux": "intraparenchymateux",
    "intra parenchymateux": "intraparenchymateux",
    "péribranchique": "péribronchique",
    "péribranchiques": "péribronchiques",
    "coup de bronche": "coupe bronchique",
    "coup de bronche qui est vasculaire": "coupe bronchique et vasculaire",
    "baréties": "Barety",
    "baréty": "Barety",
    "loge de baréties": "loge de Barety",
    "para-osophagiens": "para-oesophagiens",
    "para-osophagien": "para-oesophagien",
    "souple râle": "sous-pleurale",
    "on a encore une origine": "en accord avec une origine",
    "on a encore": "en accord avec",
    "alka négatif": "ALK négatif",
    "alka moins": "ALK négatif",
    "alk moins": "ALK négatif",
    "pdl un": "PD-L1",
    "pdl1": "PD-L1",
    "pd l1": "PD-L1",

    # ── H aspiré / H muet non capté ──────────────────────────────────────
    "yper": "hyper",
    "ypo": "hypo",
    "yperplasie": "hyperplasie",
    "ypoplasie": "hypoplasie",
    "ypertrophie": "hypertrophie",
    "yperchromatisme": "hyperchromatisme",
    "yperkératose": "hyperkératose",
    "istologique": "histologique",
    "istochimique": "histochimique",
    "istopronostique": "histopronostique",
    "istologie": "histologie",
    "istogenèse": "histogenèse",
    "épatique": "hépatique",
    "épatocellulaire": "hépatocellulaire",
    "épatocyte": "hépatocyte",
    "épatoblastome": "hépatoblastome",
    "émorragie": "hémorragie",
    "émorragique": "hémorragique",
    "émicolectomie": "hémicolectomie",
    "ystérectomie": "hystérectomie",
    "yalinisation": "hyalinisation",
    "yalinisé": "hyalinisé",
    "yaloïde": "hyaloïde",
    "ybridation": "hybridation",
    "yperbasophilie": "hyperbasophilie",
    "ypothyroïdie": "hypothyroïdie",
    "ilère": "hilaire",
    "ile": "hile",

    # ── Confusion de consonnes ────────────────────────────────────────────
    "bramchique": "bronchique",
    "blonchique": "bronchique",
    "bronquique": "bronchique",
    "troma": "stroma",
    "stoma": "stroma",
    "tromal": "stromal",
    "stomal": "stromal",
    "desmo plastique": "desmoplasique",
    "desmo plastik": "desmoplasique",
    "desmoplastik": "desmoplasique",
    "dès mo plastique": "desmoplasique",
    "chromogranine": "chromogranine",
    "chronogranine": "chromogranine",
    "sinaptophysine": "synaptophysine",
    "synaptofysine": "synaptophysine",
    "synaptophysin": "synaptophysine",
    "imuno histochimie": "immunohistochimie",
    "imuno-histochimie": "immunohistochimie",
    "immuno istochimie": "immunohistochimie",
    "carcinone": "carcinome",
    "carscinome": "carcinome",
    "karcinome": "carcinome",
    "adénocarsinome": "adénocarcinome",
    "adéno carcinome": "adénocarcinome",
    "lympome": "lymphome",
    "linphome": "lymphome",
    "limphome": "lymphome",
    "lymphôme": "lymphome",
    "sarcome": "sarcome",
    "sarcôme": "sarcome",
    "mésotheliome": "mésothéliome",
    "mésotéliome": "mésothéliome",
    "mesothéliome": "mésothéliome",
    "gliobalstome": "glioblastome",
    "glio blastome": "glioblastome",
    "fréochromocytome": "phéochromocytome",
    "féochromocytome": "phéochromocytome",
    "phéocromocytome": "phéochromocytome",
    "néfroblastome": "néphroblastome",
    "néfro blastome": "néphroblastome",
    "néfrectomie": "néphrectomie",
    "schvanome": "schwannome",
    "schwanome": "schwannome",
    "chwannome": "schwannome",

    # ── Troncature de syllabes ────────────────────────────────────────────
    "parenchymateux": "parenchymateux",
    "parenchymateuz": "parenchymateuse",
    "parenchime": "parenchyme",
    "parenquime": "parenchyme",
    "malpigien": "malpighienne",
    "malpigienne": "malpighienne",
    "malpighien": "malpighienne",
    "epiderm": "épidermoïde",
    "épiderm": "épidermoïde",
    "épidermoide": "épidermoïde",
    "adénocarcinomateux": "adénocarcinomateuse",
    "urotélial": "urothélial",
    "urothéliale": "urothélial",
    "urotéliale": "urothélial",

    # ── Homophones et assimilations ───────────────────────────────────────
    "les pidiques": "lépidique",
    "les pédiques": "lépidique",
    "lépidik": "lépidique",
    "lipidique": "lépidique",
    "l'épidique": "lépidique",
    "les pidique": "lépidique",
    "cribi forme": "cribriforme",
    "les quelles": "lesquelles",
    "des mots plastique": "desmoplasique",
    "cyber net": "cribriforme",
    "micro papillaire": "micropapillaire",
    "micro papier": "micropapillaire",
    "trabec ulaire": "trabéculaire",
    "trabe culaire": "trabéculaire",
    "trabéculer": "trabéculaire",
    "papiller": "papillaire",
    "acineuz": "acineuse",
    "acineuze": "acineuse",
    "a si neux": "acineux",
    "la si neux": "acineux",
    "mucineu": "mucineux",
    "mucineuse": "mucineuse",
    "endo métri oïde": "endométrioïde",
    "endométri oïde": "endométrioïde",
    "en dos métri oïde": "endométrioïde",
    "can a l'anal": "canal anal",
    "canal-anal": "canal anal",
    "en vaillé": "envahies",
    "en vaillée": "envahies",
    "en vahi": "envahi",
    "envaillée": "envahie",
    "en vaille": "envahie",
    "marge en vaillée": "marge envahie",
    "marges en vaillées": "marges envahies",
    "tanjante": "tangente",
    "tangent": "tangente",

    # ── Sigles et marqueurs mal transcrits ────────────────────────────────
    "p16": "p16",
    "pé 16": "p16",
    "P 16": "p16",
    "her-2": "HER2",
    "her 2": "HER2",
    "air 2": "HER2",
    "ère 2": "HER2",
    "cade": "CDX2",
    "cdx 2": "CDX2",
    "cd x 2": "CDX2",
    "c d x 2": "CDX2",
    "ck sept": "CK7",
    "ck 7": "CK7",
    "ck vingt": "CK20",
    "ck 20": "CK20",
    "ck 5/6": "CK5/6",
    "ck cinq six": "CK5/6",
    "ki 67": "Ki-67",
    "qui 67": "Ki-67",
    "qui soixante sept": "Ki-67",
    "ki soixante sept": "Ki-67",
    "khi 67": "Ki-67",
    "ttf 1": "TTF1",
    "tt f1": "TTF1",
    "t t f 1": "TTF1",
    "alf": "ALK",
    "pdl 1": "PD-L1",
    "pd l1": "PD-L1",
    "pdl1": "PD-L1",
    "pd-l 1": "PD-L1",
    "pd l 1": "PD-L1",
    "ros 1": "ROS1",
    "mlh 1": "MLH1",
    "msh 2": "MSH2",
    "msh 6": "MSH6",
    "pms 2": "PMS2",
    "cd 3": "CD3",
    "cd 20": "CD20",
    "cd vingt": "CD20",
    "cd 34": "CD34",
    "cd 117": "CD117",
    "braf": "BRAF",
    "b-raf": "BRAF",
    "b raf": "BRAF",
    "cas ras": "KRAS",
    "k ras": "KRAS",
    "nrass": "NRAS",
    "n ras": "NRAS",
    "e g f r": "EGFR",
    "i d h 1": "IDH1",
    "i d h 2": "IDH2",
    "i n i 1": "INI1",
    "pax 8": "PAX8",
    "pacs 8": "PAX8",
    "socks 10": "SOX10",
    "sox 10": "SOX10",
    "s 100": "S100",
    "s cent": "S100",
    "gâta 3": "GATA3",
    "gata 3": "GATA3",
    "a m a c r": "AMACR",
    "amacre": "AMACR",
    "wt 1": "WT1",
    "er g": "ERG",
    "dog 1": "DOG1",

    # ── Scores et éponymes mal transcrits ─────────────────────────────────
    "glison": "Gleason",
    "glisson": "Gleason",
    "gleeson": "Gleason",
    "gleasson": "Gleason",
    "brezlow": "Breslow",
    "breslo": "Breslow",
    "furman": "Fuhrman",
    "fuhrmann": "Fuhrman",
    "not in femme": "Nottingham",
    "nottingam": "Nottingham",
    "notingham": "Nottingham",
    "elstonellis": "Elston-Ellis",
    "elston elis": "Elston-Ellis",
    "scarf bloom richardson": "Scarff-Bloom-Richardson",
    "sbr": "SBR",

    # ── Corrections anatomiques et techniques ─────────────────────────────
    "exentéranée": "extemporané",
    "exentérané": "extemporané",
    "extemporannée": "extemporané",
    "extemp": "extemporané",
    "imuno": "immuno",
    "im uno": "immuno",
    "éritroplasie": "érythroplasie",
    "calcifié": "calcifié",
    "peaux de planing": "podoplanine",
    "podaux planing": "podoplanine",
    "podo planing": "podoplanine",
    "podo planine": "podoplanine",
    "calrétinin": "calrétinine",
    "désmine": "desmine",
    "dès mine": "desmine",
    "miogénine": "myogénine",
    "myo génine": "myogénine",
    "formaule": "formule",
    "colique gauche": "colique gauche",
    "ziel nelson": "Ziehl-Neelsen",
    "ziehl nelson": "Ziehl-Neelsen",
    "zièle nelsen": "Ziehl-Neelsen",
    "groco": "Grocott",
    "grosso": "Grocott",
    "grocau": "Grocott",
    "papanicolao": "Papanicolaou",
    "papanicolau": "Papanicolaou",
}

CONTEXT_BIAS_TERMS: list[str] = [
    # Marqueurs IHC (très souvent mal transcrits - priorité 1)
    "TTF1", "ALK", "PD-L1", "Ki67",
    "HER2", "CK7", "CK20", "CK5/6", "CDX2", "p16", "p40", "p63", "p53",
    "GATA3", "PAX8", "SOX10", "Melan-A", "HMB45",
    "AMACR", "P504S", "PSA", "NKX3.1", "ERG",
    "Chromogranine", "Synaptophysine",
    "RE", "RP", "MLH1", "MSH2", "MSH6", "PMS2",
    "BRAF", "KRAS", "NRAS", "EGFR", "ROS1",
    "Desmine", "DOG1", "BCL2", "Calrétinine",
    # Éponymes/Scores (critiques pour le sens clinique)
    "Gleason", "ISUP", "Scarff-Bloom-Richardson", "SBR",
    "Breslow", "Clark", "Fuhrman", "Nottingham",
    "pTNM", "FIGO", "METAVIR",
    # Termes techniques fréquemment mal transcrits (mots simples uniquement)
    "adénocarcinome", "carcinome", "épidermoïde", "urothélial",
    "mélanome", "mésothéliome", "lymphome",
    "acineux", "lépidique", "papillaire", "micropapillaire", "cribriforme",
    "trabéculaire", "mucineux", "desmoplasique",
    "koïlocytes", "dyskératose", "parakératose", "acanthose",
    "stroma", "fibro-hyalin", "myxoïde",
    # Anatomie critique
    "bronchique", "hilaire", "parenchymateuse", "périnerveux",
    "lymphovasculaire", "ganglionnaire",
    # Prélèvements
    "lobectomie", "mastectomie", "prostatectomie",
    "néphrectomie", "colectomie", "gastrectomie",
    "thyroïdectomie", "hystérectomie", "cystectomie",
    # Cytologie LBA
    "sidérophages", "polynucléaires", "neutrophiles", "éosinophiles",
    # Néoplasies intraépithéliales
    "AIN3", "CIN3",
    # Biologie moléculaire
    "FISH", "NGS",
    "IDH1", "ATRX", "H3K27M",
]


def get_context_bias() -> list[str]:
    """Retourne la liste de termes pour le context_bias Voxtral STT."""
    return CONTEXT_BIAS_TERMS


def corriger_phonetique(texte: str) -> str:
    """Applique les corrections phonetiques STT recurrentes.

    Matching insensible a la casse, avec tri par longueur decroissante
    pour eviter les remplacements partiels (une expression longue est
    traitee avant une expression courte qui la chevauche).
    """
    corrections_triees: list[tuple[str, str]] = sorted(
        CORRECTIONS_PHONETIQUES.items(),
        key=lambda item: len(item[0]),
        reverse=True,
    )

    resultat: str = texte
    for erreur, correction in corrections_triees:
        motif: str = re.escape(erreur)
        if erreur[0].isalnum():
            motif = r"\b" + motif
        if erreur[-1].isalnum():
            motif = motif + r"\b"
        resultat = re.sub(motif, correction, resultat, flags=re.IGNORECASE)

    return resultat
